name: ArchivingImageDB

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Generate dataset archive
      run: zip -r moss-db.zip ./dataset
    - name: Make Release
      run: echo "Release"
    - name: Push changes to repo
      run: |
        REMOTE=https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git config user.name "${{ github.actor }}"

        git pull ${REMOTE}
        git checkout master
        git add .
        git status
        git commit -am "Add new comment"
        git push ${REMOTE} master
